---
baseurl: ""
# excerpt_separator: "\n\n"
description: "Hi. My name is Katya Demidova, and I'd love to write more."
github_username: demidovakatya
highlighter: rouge
kramdown:
  input: GFM
markdown: kramdown
paginate_path: /:num
permalink: "/blog/:title"
title: "My awesome blog"
url: "http://demidovakatya.github.io"
defaults:
  -
    scope:
      path: "_drafts"
      type: "posts"
    values:
      layout: "post"
      author: "Katya Demidova"
timezone: "Europe/Moscow"
