---
baseurl: ""
excerpt_separator: "\n\n"
description: ""
github_username: demidovakatya
highlighter: rouge
kramdown:
  input: GFM
markdown: kramdown
paginate_path: /:num
permalink: "/blog/:title"
title: "My awesome blog"
url: "http://demidovakatya.github.io"
